# Generated by Django 2.0 on 2017-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CM', '0002_auto_20171215_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkDest', models.GenericIPAddressField(protocol='ipv4')),
                ('netmask', models.GenericIPAddressField(protocol='ipv4')),
                ('nextHop', models.GenericIPAddressField(protocol='ipv4')),
                ('interface', models.GenericIPAddressField(protocol='ipv4')),
                ('metric', models.IntegerField()),
            ],
        ),
    ]
