# Generated by Django 2.0 on 2017-12-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0004_auto_20171215_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingtable',
            name='id',
        ),
        migrations.AlterField(
            model_name='routingtable',
            name='network_dest',
            field=models.GenericIPAddressField(primary_key=True, protocol='ipv4', serialize=False),
        ),
    ]
